version: '3.8'
services:

  rebalancer:
    container_name: rebalancer
    image: 679752396206.dkr.ecr.us-east-2.amazonaws.com/chain-rebalancer-api:latest
    build: .
    restart: always
    ports:
      - "8080:8080"
    networks:
      - connext-net

networks:
  connext-net:
